# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
env:
  RUBY_VERSION: 3.0.2
  POSTGRES_USER: app2
  POSTGRES_PASSWORD: Fa1ry7a1l
  POSTGRES_DB: DragonsAndGems
  DATABASE_URL: "postgres://${{ env.POSTGRES_USER }}:${{ env.POSTGRES_PASSWORD }}@46.8.19.64:5432/${{ env.POSTGRES_DB }}"
  RAILS_ENV: test

name: Rails tests
on: [push,pull_request]
jobs:
  rspec-test:
    name: RSpec
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: Install dependencies
        run: |
          gem install bundler
          bundler install
      - name: Create database
        run: |
          bin/rails db:create RAILS_ENV=test
          bin/rails db:migrate RAILS_ENV=test
      - name: Run tests
        run: bundler exec rake
  deploy:
    runs-on: self-hosted
    needs: rspec-test
    steps:
      - name: Run
        run: scripts/deploy.sh
